baseURL = 'https://1water1.top/'
languageCode = 'zh-cn'
title = 'Water'
theme = 'hugo-theme-stack'

[params]
    description = "这是一个用 Hugo + Stack 搭建的运维博客"
    defaultTheme = "auto"
    mainSections = ["posts"] 
    [params.sidebar]
        emoji = "🐧"
        subtitle = "运维 /water "
        
        [params.sidebar.avatar]
            enabled = true
            local = true
            src = "img/avatar.jpg" 

    [params.social]
        [params.social.github]
            username = "waterfile130-cell"
            icon = "github"
    
    [params.article]
        description = true
        [params.article.license]
            enabled = true
            default = true

# --- 菜单栏 (暂时去掉了 icon 设置，保证不报错) ---
[[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params.comments.giscus]
    enable = true
    repo = "waterfile130-cell/comments"  # 刚才填的仓库名
    repoId = "R_kgDOQurkiQ"
    category = "General"
    categoryId = "DIC_kwDOQurkic4C0OlZ"
    mapping = "pathname"
    reactionsEnabled = true
    emitMetadata = false
    inputPosition = "bottom"
    theme = "light"