name: Deploy Hugo Site to Pages

on:
  push:
    branches:
      - main  # 确保这里是你存放源码的分支名，通常是 main 或 master

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一个部署任务
concurrency:
  group: "pages"
  cancel-in-progress: true

# 默认使用 bash
defaults:
  run:
    shell: bash

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0 # 这里可以指定较新的版本
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # 必须下载主题子模块

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # <--- 关键！必须开启扩展版才能编译 SCSS

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4